nginx:
  image: nginx
  ports:
   - "80:80"
  restart: always
  working_dir: /static
  entrypoint: nginx -c /app/nginx.conf
  volumes:
   - './:/app:ro'
  links:
    - app
app:
  build: .
  expose:
   - "9090"
  restart: always
  working_dir: /app
  entrypoint: bash -c "bundle install --local && exec websocketd --port 9090 --staticdir=./static --passenv GEM_HOME,BUNDLE_APP_CONFIG,RUBY_MAJOR,RUBYGEMS_VERSION,BUNDLE_BIN,BUNDLE_PATH,RUBY_VERSION,BUNDLER_VERSION,PATH bundle exec ruby /app/chat.rb"
  volumes:
   - '.:/app:ro'
  links:
    - redis

redis:
  image: redis
  restart: always
